### ISSUE TITLE
The URL does shows 404.

### ISSUE THREAD

**Issue by efft** [ryanflorence/react-training#19]

**Comment by sejoker** [comment]
more precisely this url: http://rpflorence.github.io/react-training/code

**Comment by efft** [comment]
Thanks!

**Comment by efft** [comment]
Sorry, I still cant see it.

[image: Inline image 1]

**Comment by ryanblakeley** [comment]
Very 404.

**Comment by drazic1** [comment]
All demo links should be updated to http://ryanflorence.github.io/react-training/code/ instead of http://rpflorence.github.io/react-training/code

There's already a pull request (https://github.com/ryanflorence/react-training/pull/12) to solve this issue

**Comment by knomedia** [comment]
closed in #12
