### ISSUE TITLE
Integration with a jQuery Slider

### ISSUE THREAD

**Issue by edygar** [ryanflorence/react-training#20]
I couldn't figure out how to integration with an jQuery Slider, such as the bxSlider or [slick](http://kenwheeler.github.io/slick/) (which has an [port](https://github.com/akiran/react-slick/) undergoing to react). This is different from the Dialog sample, the sliders plug-in adds, removes and modifies nodes at 2nd level below to my component.

My component would have a `render()` which would return a self-closing `<ul/>`, on `componentDidMount` I would have to map each this.prop.children to an `<li>` created by jQuery and them `React.render` the children at this node. Is that right? I can't find examples of it out there.

**Comment by knomedia** [comment]
The basic concepts of a portal would be the same. You stop react's render tree, and then potentially start a new one using `this.props.children` objects to be passed along. If your DOM mutating library is adding multiple nodes that shouldn't be an issue as you've stopped the current render tree.

For details on specifics with other libraries you might get more timely responses on stackoverflow, or the react slack channel (http://www.reactiflux.com/)

**Comment by edygar** [comment]
Thank you!
